import {
  DEFAULT_STRINGS,
  type FeedbackWidgetStrings,
  slavicPluralForm,
} from "./ui/strings";

/**
 * Ready-made label bundles.
 *
 * ```ts
 * import { labels } from "sluglist/labels";
 * mountFeedbackWidget(widget, { strings: labels.uk });
 * ```
 *
 * Spread one to override a single string:
 * `{ ...labels.uk, sendButton: "…" }`. Anything you leave out falls back to
 * English, so a bundle can never leave the UI with an empty button.
 *
 * The locale is chosen by you, not sniffed from the browser: which language
 * your testers read is a property of the engagement, not of their user agent.
 *
 * Translation notes: only widget chrome is translated. Your own copy — the
 * category chips, checklist titles, form labels — stays yours; it is passed
 * through config and is not part of a bundle.
 */

/** English — the default bundle; identical to shipping no `strings` at all. */
export const en: FeedbackWidgetStrings = DEFAULT_STRINGS;

export const ru: FeedbackWidgetStrings = {
  ...DEFAULT_STRINGS,
  addScreenshot: "+ Добавить скриншот",
  annotateArrow: "Стрелка",
  annotateBox: "Рамка",
  annotateDone: "Готово",
  annotateText: "Текст",
  annotateUndo: "Отменить",
  areaHint: "Выделите область перетаскиванием. Esc — отмена.",
  attachFile: "+ Прикрепить файл",
  attachDrop: "Отпустите файлы, чтобы прикрепить",
  attachRejectedType: "{name}: такой тип файла не принимается",
  attachRejectedSize: "{name} весит {size} — лимит {limit}",
  attachRejectedCount: "Можно прикрепить не больше {n} файлов к одной проблеме",
  attachRejectedEmpty: "{name} — пустой файл",
  attachRemove: "Удалить файл",
  attachScreenshot: "Приложить скриншот",
  buttonLabel: "Отзыв",
  cancel: "Отмена",
  capturing: "Снимаем...",
  close: "Закрыть",
  categoryBug: "Баг",
  categoryDesign: "Дизайн",
  categoryIdea: "Идея",
  checklistButton: "Чек-лист",
  checklistDone: "Готово",
  checklistFail: "Сообщить",
  checklistOpen: "Открыть",
  checklistPass: "Ок",
  checklistSkip: "Пропустить",
  checklistItemIssue: "Сообщить о проблеме",
  checklistItemIssueLink: "проблема {id}",
  checklistHere: "Вы здесь",
  checklistAutosaved: "Всё сохраняется автоматически",
  checklistSummaryChecked: "{done} из {total} проверено",
  checklistSummaryDone: "{n} проверено",
  checklistSummaryIssueOne: "{n} проблема",
  checklistSummaryIssueFew: "{n} проблемы",
  checklistSummaryIssueMany: "{n} проблем",
  checklistSummaryLeft: "осталось {n}",
  checklistUncheckIssue:
    "По этому пункту уже отправлена проблема ({id}). Снятие отметки убирает вашу оценку — сама проблема останется сохранённой. Продолжить?",
  commentPlaceholder: "Опишите проблему...",
  placeholderBug: "Опишите проблему...",
  placeholderDesign: "Что выглядит не так?...",
  placeholderIdea: "Опишите вашу идею...",
  deliveryFailed: "Проблема {id}: не удалось загрузить",
  dialogTitle: "Новая проблема",
  dismiss: "Скрыть кнопку отзыва",
  elementHint: "Кликните по элементу, чтобы сообщить о нём. Esc — отмена.",
  formChoose: "Выберите…",
  formRequired: "Обязательное поле",
  formInvalidEmail: "Введите корректный email",
  formSessionTitle: "Немного о вас",
  imageAlt: "Скриншот {n}",
  frameAlt: "Кадр {n}",
  menuArea: "Выделить область",
  menuElement: "Выбрать элемент",
  menuFullpage: "Скриншот всей страницы",
  menuNoScreenshot: "Комментарий без скриншота",
  menuRecord: "Записать шаги",
  noScreenshot: "Без скриншота",
  recording: "Запись · кадров: {id}",
  recordingCancel: "Отмена",
  recordingFrames: "кадров: {id}",
  recordingClip: "Клип {n}",
  recordingFrameOne: "{n} кадр",
  recordingFrameFew: "{n} кадра",
  recordingFrameMany: "{n} кадров",
  recordingHint: "Кадры снимаются на кликах и переходах",
  recordingLimit: "Достигнут лимит кадров ({id})",
  recordingRemove: "Удалить запись",
  recordingSnap: "+ Кадр",
  removeScreenshot: "Удалить скриншот",
  recordingStop: "Стоп и описать",
  reportProblem: "Сообщить о проблеме",
  retry: "Повторить",
  saved: "Проблема {id} сохранена",
  screenshotFailed: "Скриншот не получился — отправляем без него",
  sending: "Отправляем проблему {id}...",
  send: "Отправить",
  pluralForm: slavicPluralForm,
};

export const uk: FeedbackWidgetStrings = {
  ...DEFAULT_STRINGS,
  addScreenshot: "+ Додати знімок",
  annotateArrow: "Стрілка",
  annotateBox: "Рамка",
  annotateDone: "Готово",
  annotateText: "Текст",
  annotateUndo: "Скасувати",
  areaHint: "Виділіть область перетягуванням. Esc — скасувати.",
  attachFile: "+ Прикріпити файл",
  attachDrop: "Відпустіть файли, щоб прикріпити",
  attachRejectedType: "{name}: такий тип файлу не приймається",
  attachRejectedSize: "{name} важить {size} — ліміт {limit}",
  attachRejectedCount: "Можна прикріпити щонайбільше {n} файлів до однієї проблеми",
  attachRejectedEmpty: "{name} — порожній файл",
  attachRemove: "Видалити файл",
  attachScreenshot: "Додати знімок екрана",
  buttonLabel: "Відгук",
  cancel: "Скасувати",
  capturing: "Знімаємо...",
  close: "Закрити",
  categoryBug: "Баг",
  categoryDesign: "Дизайн",
  categoryIdea: "Ідея",
  checklistButton: "Чек-лист",
  checklistDone: "Готово",
  checklistFail: "Повідомити",
  checklistOpen: "Відкрити",
  checklistPass: "Ок",
  checklistSkip: "Пропустити",
  checklistItemIssue: "Повідомити про проблему",
  checklistItemIssueLink: "проблема {id}",
  checklistHere: "Ви тут",
  checklistAutosaved: "Усе зберігається автоматично",
  checklistSummaryChecked: "{done} з {total} перевірено",
  checklistSummaryDone: "{n} перевірено",
  checklistSummaryIssueOne: "{n} проблема",
  checklistSummaryIssueFew: "{n} проблеми",
  checklistSummaryIssueMany: "{n} проблем",
  checklistSummaryLeft: "залишилось {n}",
  checklistUncheckIssue:
    "За цим пунктом уже надіслано проблему ({id}). Знявши позначку, ви приберете свою оцінку — сама проблема залишиться збереженою. Продовжити?",
  commentPlaceholder: "Опишіть проблему...",
  placeholderBug: "Опишіть проблему...",
  placeholderDesign: "Що виглядає не так?...",
  placeholderIdea: "Опишіть свою ідею...",
  deliveryFailed: "Проблема {id}: не вдалося завантажити",
  dialogTitle: "Нова проблема",
  dismiss: "Сховати кнопку відгуку",
  elementHint: "Клацніть елемент, щоб повідомити про нього. Esc — скасувати.",
  formChoose: "Оберіть…",
  formRequired: "Обов'язкове поле",
  formInvalidEmail: "Введіть коректний email",
  formSessionTitle: "Трохи про вас",
  imageAlt: "Знімок {n}",
  frameAlt: "Кадр {n}",
  menuArea: "Виділити область",
  menuElement: "Обрати елемент",
  menuFullpage: "Знімок усієї сторінки",
  menuNoScreenshot: "Коментар без знімка",
  menuRecord: "Записати кроки",
  noScreenshot: "Без знімка",
  recording: "Запис · кадрів: {id}",
  recordingCancel: "Скасувати",
  recordingFrames: "кадрів: {id}",
  recordingClip: "Кліп {n}",
  recordingFrameOne: "{n} кадр",
  recordingFrameFew: "{n} кадри",
  recordingFrameMany: "{n} кадрів",
  recordingHint: "Кадри знімаються на кліках і переходах",
  recordingLimit: "Досягнуто ліміт кадрів ({id})",
  recordingRemove: "Видалити запис",
  recordingSnap: "+ Кадр",
  removeScreenshot: "Видалити знімок",
  recordingStop: "Стоп і описати",
  reportProblem: "Повідомити про проблему",
  retry: "Повторити",
  saved: "Проблему {id} збережено",
  screenshotFailed: "Знімок не вдався — надсилаємо без нього",
  sending: "Надсилаємо проблему {id}...",
  send: "Надіслати",
  pluralForm: slavicPluralForm,
};

export const es: FeedbackWidgetStrings = {
  ...DEFAULT_STRINGS,
  addScreenshot: "+ Añadir captura",
  annotateArrow: "Flecha",
  annotateBox: "Recuadro",
  annotateDone: "Listo",
  annotateText: "Texto",
  annotateUndo: "Deshacer",
  areaHint: "Arrastra para seleccionar un área. Esc para cancelar.",
  attachFile: "+ Adjuntar archivo",
  attachDrop: "Suelta los archivos para adjuntarlos",
  attachRejectedType: "{name}: este tipo de archivo no se acepta",
  attachRejectedSize: "{name} pesa {size} — el límite es {limit}",
  attachRejectedCount: "Puedes adjuntar hasta {n} archivos por incidencia",
  attachRejectedEmpty: "{name} está vacío",
  attachRemove: "Quitar archivo",
  attachScreenshot: "Adjuntar captura",
  buttonLabel: "Feedback",
  cancel: "Cancelar",
  capturing: "Capturando...",
  close: "Cerrar",
  categoryBug: "Error",
  categoryDesign: "Diseño",
  categoryIdea: "Idea",
  checklistButton: "Checklist",
  checklistDone: "Listo",
  checklistFail: "Reportar",
  checklistOpen: "Abrir",
  checklistPass: "Ok",
  checklistSkip: "Omitir",
  checklistItemIssue: "Reportar un problema",
  checklistItemIssueLink: "incidencia {id}",
  checklistHere: "Estás aquí",
  checklistAutosaved: "Todo se guarda automáticamente",
  checklistSummaryChecked: "{done} de {total} verificados",
  checklistSummaryDone: "{n} verificados",
  checklistSummaryIssueOne: "{n} incidencia",
  checklistSummaryIssueMany: "{n} incidencias",
  checklistSummaryLeft: "quedan {n}",
  checklistUncheckIssue:
    "Este punto tiene una incidencia reportada ({id}). Desmarcarlo borra tu veredicto — la incidencia se mantiene guardada. ¿Continuar?",
  commentPlaceholder: "Describe el problema...",
  placeholderBug: "Describe el problema...",
  placeholderDesign: "¿Qué se ve mal?...",
  placeholderIdea: "Describe tu idea...",
  deliveryFailed: "Incidencia {id}: fallo al subir",
  dialogTitle: "Nueva incidencia",
  dismiss: "Ocultar el botón de feedback",
  elementHint: "Haz clic en un elemento para reportarlo. Esc para cancelar.",
  formChoose: "Elige…",
  formRequired: "Este campo es obligatorio",
  formInvalidEmail: "Introduce un email válido",
  formSessionTitle: "Algunos datos",
  imageAlt: "Captura {n}",
  frameAlt: "Fotograma {n}",
  menuArea: "Seleccionar área",
  menuElement: "Seleccionar elemento",
  menuFullpage: "Captura de la página completa",
  menuNoScreenshot: "Comentario sin captura",
  menuRecord: "Grabar pasos",
  noScreenshot: "Sin captura para esta incidencia",
  recording: "Grabando · {id} fotogramas",
  recordingCancel: "Cancelar",
  recordingFrames: "{id} fotogramas",
  recordingClip: "Clip {n}",
  recordingFrameOne: "{n} fotograma",
  recordingFrameMany: "{n} fotogramas",
  recordingHint: "Los fotogramas se capturan en clics y navegación",
  recordingLimit: "Límite de fotogramas alcanzado ({id})",
  recordingRemove: "Eliminar grabación",
  recordingSnap: "+ Fotograma",
  removeScreenshot: "Quitar captura",
  recordingStop: "Parar y describir",
  reportProblem: "Reportar un problema",
  retry: "Reintentar",
  saved: "Incidencia {id} guardada",
  screenshotFailed: "La captura falló — se envía sin ella",
  sending: "Enviando la incidencia {id}...",
  send: "Enviar",
};

export const de: FeedbackWidgetStrings = {
  ...DEFAULT_STRINGS,
  addScreenshot: "+ Screenshot hinzufügen",
  annotateArrow: "Pfeil",
  annotateBox: "Rahmen",
  annotateDone: "Fertig",
  annotateText: "Text",
  annotateUndo: "Rückgängig",
  areaHint: "Ziehen, um einen Bereich zu wählen. Esc zum Abbrechen.",
  attachFile: "+ Datei anhängen",
  attachDrop: "Dateien hier ablegen",
  attachRejectedType: "{name}: dieser Dateityp wird nicht akzeptiert",
  attachRejectedSize: "{name} ist {size} groß — das Limit liegt bei {limit}",
  attachRejectedCount: "Pro Meldung sind höchstens {n} Dateien möglich",
  attachRejectedEmpty: "{name} ist leer",
  attachRemove: "Datei entfernen",
  attachScreenshot: "Screenshot anhängen",
  buttonLabel: "Feedback",
  cancel: "Abbrechen",
  capturing: "Aufnahme läuft...",
  close: "Schließen",
  categoryBug: "Fehler",
  categoryDesign: "Design",
  categoryIdea: "Idee",
  checklistButton: "Checkliste",
  checklistDone: "Fertig",
  checklistFail: "Melden",
  checklistOpen: "Öffnen",
  checklistPass: "Ok",
  checklistSkip: "Überspringen",
  checklistItemIssue: "Problem melden",
  checklistItemIssueLink: "Meldung {id}",
  checklistHere: "Sie sind hier",
  checklistAutosaved: "Alles wird automatisch gespeichert",
  checklistSummaryChecked: "{done} von {total} geprüft",
  checklistSummaryDone: "{n} geprüft",
  checklistSummaryIssueOne: "{n} Problem",
  checklistSummaryIssueMany: "{n} Probleme",
  checklistSummaryLeft: "noch {n}",
  checklistUncheckIssue:
    "Zu diesem Punkt wurde bereits ein Problem gemeldet ({id}). Das Abwählen löscht Ihr Urteil — die Meldung selbst bleibt gespeichert. Fortfahren?",
  commentPlaceholder: "Beschreiben Sie das Problem...",
  placeholderBug: "Beschreiben Sie das Problem...",
  placeholderDesign: "Was sieht falsch aus?...",
  placeholderIdea: "Beschreiben Sie Ihre Idee...",
  deliveryFailed: "Meldung {id}: Upload fehlgeschlagen",
  dialogTitle: "Neue Meldung",
  dismiss: "Feedback-Button ausblenden",
  elementHint: "Auf ein Element klicken, um es zu melden. Esc zum Abbrechen.",
  formChoose: "Auswählen…",
  formRequired: "Pflichtfeld",
  formInvalidEmail: "Bitte eine gültige E-Mail-Adresse eingeben",
  formSessionTitle: "Ein paar Angaben",
  imageAlt: "Screenshot {n}",
  frameAlt: "Bild {n}",
  menuArea: "Bereich wählen",
  menuElement: "Element wählen",
  menuFullpage: "Screenshot der ganzen Seite",
  menuNoScreenshot: "Kommentar ohne Screenshot",
  menuRecord: "Schritte aufzeichnen",
  noScreenshot: "Kein Screenshot für diese Meldung",
  recording: "Aufnahme · {id} Bilder",
  recordingCancel: "Abbrechen",
  recordingFrames: "{id} Bilder",
  recordingClip: "Clip {n}",
  recordingFrameOne: "{n} Bild",
  recordingFrameMany: "{n} Bilder",
  recordingHint: "Bilder werden bei Klicks und Navigation aufgenommen",
  recordingLimit: "Bildlimit erreicht ({id})",
  recordingRemove: "Aufnahme entfernen",
  recordingSnap: "+ Bild",
  removeScreenshot: "Screenshot entfernen",
  recordingStop: "Stoppen & beschreiben",
  reportProblem: "Problem melden",
  retry: "Erneut versuchen",
  saved: "Meldung {id} gespeichert",
  screenshotFailed: "Screenshot fehlgeschlagen — wird ohne gesendet",
  sending: "Meldung {id} wird gesendet...",
  send: "Senden",
};

/** Every bundle, keyed by language tag. */
export const labels = { en, ru, uk, es, de };

export type LabelLocale = keyof typeof labels;
